# --- Day 7: Laboratories ---

# You thank the cephalopods for the help and exit the trash compactor, finding yourself in the
# [familiar](https://adventofcode.com/2024/day/6) [halls](https://adventofcode.com/2018/day/4) of
# a North Pole research wing.
#
# Based on the large sign that says "teleporter hub", they seem to be researching teleportation;
# you can't help but try it for yourself and step onto the large yellow teleporter pad.
#
# Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is
# the teleporter. Unfortunately, the teleporter seems to be leaking
# [magic smoke](https://en.wikipedia.org/wiki/Magic_smoke).
#
# Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment
# lying around. After connecting one of the diagnostic tools, it helpfully displays error code
# 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.
#
# You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters
# the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass
# freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam
# is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate
# right of the splitter.
#
# For example:
#
# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
#
# In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:
#
# .......S.......
# .......|.......
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
#
# At that point, the original beam stops, and two new beams are emitted from the splitter:
#
# .......S.......
# .......|.......
# ......|^|......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
#
# Those beams continue downward until they reach more splitters:
#
# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
#
# At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:
#
# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
#
# This process continues until all of the tachyon beams reach a splitter or exit the manifold:
#
# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# .....|.|.|.....
# ....|^|^|^|....
# ....|.|.|.|....
# ...|^|^|||^|...
# ...|.|.|||.|...
# ..|^|^|||^|^|..
# ..|.|.|||.|.|..
# .|^|||^||.||^|.
# .|.|||.||.||.|.
# |^|^|^|^|^|||^|
# |.|.|.|.|.|||.|
#
# To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.
#
# Analyze your manifold diagram. How many times will the beam be split?
#

# --- Part Two ---

# With your analysis of the manifold complete, you begin fixing the teleporter. However, as you
# open the side of the teleporter to replace the broken manifold, you are surprised to discover
# that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

# With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A
# tachyon particle takes both the left and right path of each splitter encountered.

# Since this is impossible, the manual recommends the many-worlds interpretation of quantum
# tachyon splitting: each time a particle reaches a splitter, it's actually time itself which
# splits. In one timeline, the particle went left, and in the other timeline, the particle went
# right.

# To fix the manifold, what you really need to know is the number of timelines active after a
# single particle completes all of its possible journeys through the manifold.

# In the above example, there are many timelines. For instance, there's the timeline where the
# particle always went left:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ...|^.^...^....
# ...|...........
# ..|^.^...^.^...
# ..|............
# .|^...^.....^..
# .|.............
# |^.^.^.^.^...^.
# |..............

# Or, there's the timeline where the particle alternated going left and right at each splitter:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# ......^|^......
# .......|.......
# .....^|^.^.....
# ......|........
# ....^.^|..^....
# .......|.......
# ...^.^.|.^.^...
# .......|.......
# ..^...^|....^..
# .......|.......
# .^.^.^|^.^...^.
# ......|........

# Or, there's the timeline where the particle ends up at the same point as the alternating
# timeline, but takes a totally different path to get there:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ....^|^...^....
# .....|.........
# ...^.^|..^.^...
# ......|........
# ..^..|^.....^..
# .....|.........
# .^.^.^|^.^...^.
# ......|........

# In this example, in total, the particle ends up on 40 different timelines.

# Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In
# total, how many different timelines would a single tachyon particle end up on?


require_relative 'input'

day = __FILE__[/\d+/].to_i(10)
input = Input.for_day(day, 2025)

while ARGV[0]
  case ARGV.shift
  when 'test'
    testing = true
  when 'debug'
    debugging = true
  end
end

if testing
  input = <<~END
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  END
  expected = 21
  expected2 = 40
else
  puts "solving day #{day} from input"
end

tachyon = []
quantum = []
xform = { 'S' => 1, '.' => 0, '^' => '^' }
width = nil

part1 = 0
part2 = 0
input.each_line(chomp: true) do |line|
  puts line if debugging
  tachyon << line
  quantum << line.chars.map { xform[_1] }
  width ||= line.length
end

# Part1 - Tachyon
tachyon.each.with_index do |row, idx|
  if idx.zero?
    row.tr!('S','|')
    next
  end

  width.times do |pos|
    case row[pos]
    when '.'
      if tachyon[idx-1][pos] == '|'
        row[pos] = '|'
      end
    when '^'
      if tachyon[idx-1][pos] == '|'
        row[pos-1] = row[pos+1] = '|'
        part1 += 1
      end
    when '|'
      nil
    end
  end
end

puts "Part 1: ", part1
if testing && expected
  if expected == part1
    puts "GOOD"
  else
    puts "Expected #{expected}"
    exit 1
  end
end

puts quantum.map(&:join) if debugging

# Part2 - Quantum
quantum.each.with_index do |row, idx|
  if idx.zero?
    next
  end

  width.times do |pos|
    case row[pos]
    when Integer
      if Integer === quantum[idx-1][pos]
        row[pos] += quantum[idx-1][pos]
      end
    when '^'
      if Integer === (s = quantum[idx-1][pos])
        row[pos-1] += s
        row[pos+1] += s
      end
    end
  end

  puts quantum.map(&:join),nil if debugging

end
p quantum.last if debugging
part2 = quantum.last.sum

puts "Part 2: ", part2
if testing && expected2
  if expected2 == part2
    puts "GOOD"
  else
    puts "Expected #{expected2}"
    exit 1
  end
end
